const services = [
  {
    id: 'exile',
    name: 'Arma 3 Exile',
    address: 'greenroomgameserver.com',
    ports: [24666],
    start: '',
    stop: '',
  },
  {
    id: 'tanoa',
    name: 'Arma 3 Tanoa',
    address: 'greenroomgameserver.com',
    ports: [25666],
    start: '',
    stop: '',
  },
  {
    id: 'chernarus',
    name: 'Arma 3 Chernarus',
    address: 'greenroomgameserver.com',
    ports: [26666],
    start: '',
    stop: '',
  },
  {
    id: '7d2d',
    name: '7 Days 2 Die',
    address: 'greenroomgameserver.com',
    ports: [26900, 26910, 26915],
    start: '',
    stop: '',
  },
  {
    id: 'rust',
    name: 'Rust',
    address: 'greenroomgameserver.com',
    ports: [28015, 28016],
    start: '',
    stop: '',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    address: 'greenroomgameserver.com',
    ports: [25565],
    start: '',
    stop: '',
  },
  {
    id: 'redis',
    name: 'Redis',
    address: 'greenroomgameserver.com',
      ports: [6379],
    start: '',
    stop: '',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    address: 'greenroomgameserver.com',
    ports: [3306],
    start: '',
    stop: '',
  },
];

module.exports = services;
